export const color=
{
    COLOR_PRIMARY:"#f96163",
    COLOR_LIGHT:"#fff",
    COLOR_DARK:"#000",
    COLOR_DARK_ALT:"#262626"
};

// Sản phẩm ở đây
export const products =
[
    {
        id: "01",
        name: "Laptop MSI Gaming Stealth 16 Mercedes",
        image: require("../../../assets/images/p2.png"),
        rating: "4.2",
        information: "AMG A1VGG-293VN U9 185H/AI/32GB/2TB",
        color: "Xám",
        price: "67.990.000đ",
        cpu: "Intel Core Ultra 9 Meteor Lake - 185H",
        ram: "32 GB DDR5 2 khe",
        storage: "2 TB SSD NVMe PCIe",
        screen: "16 inch",
        gpu: "Radeon Graphics",
        weight: "1.99 kg",
        pkien:"Bộ sạc/ Chuột gaming",
        bhanh:"24 tháng",
        udai:"Voucher 600k",
        category:"Laptop"
    },
    {
        id:"02",
        name:"Laptop Lenovo Gaming Legion 9",
        image: require("../../../assets/images/p3.png"),
        rating:"4.2",
        information:"16IRX8 i9 13980HX/AI/64GB/2TB",
        color:"Đen",
        price:"135.990.000₫",
        cpu: "16IRX8 i9",
        ram: "16GB DDR4",
        storage: "512GB SSD NVMe PCIe",
        screen: "15.6 inch",
        gpu: "Radeon Graphics",
        weight: "2.14 kg",
        pkien:"Bộ sạc/ Chuột gaming",
        bhanh:"24 tháng",
        udai:"Voucher 600k",
        category:"Laptop"
    },
    {
        id:"03",
        name:"Laptop Acer Nitro 5 Tiger Gaming",
        image: require("../../../assets/images/3.jpg"),
        rating:"4.8",
        information:" i5 12500H/8GB/512GB SSD/GeForce RTX 3050",
        color:"Đen",
        price:"20.990.000 ₫",
        cpu: "Intel Core i5 Alder Lake - 12500H",
        ram: "8 GB DDR4 2 khe ",
        storage: "512 GB SSD NVMe PCIe/Max 1TB",
        screen: "15.6 inch",
        gpu: "Radeon Graphics",
        weight: "2.5 kg",
        pkien:"Bộ sạc/ Chuột gaming",
        bhanh:"24 tháng",
        udai:"Voucher 600k",
        category:"Laptop"
    },
    {
        id:"04",
        name:"Laptop Asus Vivobook",
        image: require("../../../assets/images/p4.jpg"),
        rating:"4.5",
        information:"E1404FA-NK186W R5 7520U/16GB/512GB/14",
        color:"Đen",
        price:"12.290.000 ₫",
        cpu: "AMD Ryzen 5 7520U",
        ram: "16GB LPDDR5",
        storage: "512GB SSD NVMe PCIe",
        screen: "15.6 inch",
        gpu: "Radeon Graphics",
        weight: "1.6kg",
        pkien:"Bộ sạc/ Chuột gaming",
        bhanh:"2 Năm",
        udai:"Voucher 600k",
        category:"Laptop"
    },
    {
        id:"05",
        name:"Laptop MSI Modern 15 B12MO-487VN",
        image: require("../../../assets/images/p5.jpg"),
        rating:"4.4",
        information:"I7-1255U/16GB/512GB PCIE/15.6 FHD/WIN11",
        color:"Đen",
        price:"14.990.000 đ",
        cpu: "Intel Core i7 Alder Lake - 1255U",
        ram: "16GB DDR4 ",
        storage: "512GB SSD NVMe PCIe",
        screen: "15.6 inch",
        gpu: "Radeon Graphics",
        weight: "1.7 kg",
        pkien:"Bộ sạc/ Chuột gaming",
        bhanh:"2 Năm",
        udai:"Voucher 600k ",
        category:"Laptop"
    },
    {
        id:"06",
        name:"Apple MacBook Air M1 256GB 2020",
        image: require("../../../assets/images/p6.jpg"),
        rating:"4.5",
        information:"M1 256GB 2020 I Chính hãng Apple Việt Nam",
        color:"Xám, Bạc",
        price:"18.490.000 đ",
        cpu: "Apple M1",
        ram: "8 GB",
        storage: "256 GB SSD",
        screen: "13.3 inch",
        gpu: "Radeon Graphics",
        weight: "1.29 kg",
        pkien:"Bộ sạc/ bút",
        bhanh:"24 tháng",
        udai:"Voucher 600k",
        category:"Laptop"
    },
]