export const ThanhPho = [
    'Hồ Chí Minh',
    'Hà Nội',
    'Đà Nẵng',
    'Cần Thơ',
    'Nha Trang',
    'Hải Phòng',
    'Huế',
    'Biên Hòa',
    'Vũng Tàu',
    'Thủ Dầu Một',
    'Đà Lạt',
    'Qui Nhơn'
  ];
  
  export const QuocGia = [
    'Việt Nam',
    'Trung Quốc',
    'Nhật Bản',
    'Hàn Quốc',
    'Ấn Độ',
    'Thái Lan',
    'Malaysia',
    'Singapore',
    'Indonesia',
    'Philippines',
    'Bangladesh',
    'Pakistan'
  ];
  
  export const Tinh = [
    'An Giang',
    'Bà Rịa - Vũng Tàu',
    'Bắc Giang',
    'Bắc Ninh',
    'Bến Tre',
    'Bình Dương',
    'Bình Phước',
    'Bình Thuận',
    'Cà Mau',
    'Đắk Lắk',
    'Đắk Nông',
    'Điện Biên',
    'Đồng Nai',
    'Đồng Tháp',
    'Gia Lai',
    'Hà Giang',
    'Hà Nam',
    'Hà Tĩnh',
    'Hải Dương',
    'Hải Phòng',
    'Hồ Chí Minh',
    'Hòa Bình',
    'Hưng Yên',
    'Khánh Hòa',
    'Kiên Giang',
    'Kon Tum',
    'Lâm Đồng',
    'Lạng Sơn',
    'Lào Cai',
    'Nam Định',
    'Ninh Bình',
    'Ninh Thuận',
    'Phú Thọ',
    'Phú Yên',
    'Quảng Bình',
    'Quảng Nam',
    'Quảng Ngãi',
    'Quảng Ninh',
    'Sóc Trăng',
    'Sơn La',
    'Tây Ninh',
    'Thái Bình',
    'Thái Nguyên',
    'Thanh Hóa',
    'Thừa Thiên - Huế',
    'Tiền Giang',
    'Vĩnh Long',
    'Vĩnh Phúc',
    'Yên Bái'
  ];